### ISSUE TITLE
Bug: generated `ed25519` key with the `rstuf key generate` command is not loaded properly by securesystemslib

### ISSUE THREAD

**Issue by MVrachev** [repository-service-tuf/repository-service-tuf-cli#257]
### What happened?

I generated an `ed25519` key with the `rstuf key generate` command.

Then, I tried loading the public portion with `securesystemslib.import interface.import_publickeys_from_file` and securesystemslib recognized the key as an `RSA` key instead of `ed25519` key and as a result it failed to load it.

I used the default key type when I generated it which is `ed25519`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kairoaraujo** [comment]
https://app.codecov.io/gh/vmware/repository-service-tuf-cli/blob/main/repository_service_tuf/cli/key/generate_key.py

**Comment by KAUTH** [comment]
Hm interesting, but I had tried generating a `ed25519` and loading it in `rstuf admin ceremony` for:
- an `rsa` key - if failed as expected
- an `ed25519` key - it successfully loaded it as expected
but of course that was using a _private_ key

I did some research and the reason probably why `securesystemslib` recognized the key as an `RSA` key instead of `ed25519` key is because the `key_types` argument was not passed to `import_publickeys_from_file`, thus taking the default `RSA`, see [docstring](https://github.com/secure-systems-lab/securesystemslib/blob/main/securesystemslib/interface.py#L971)

Try:
```python
from securesystemslib.interface import import_publickeys_from_file
import_publickeys_from_file(["id_ed25519.pub"], key_types=["ed25519"])
```
it should work

**Comment by KAUTH** [comment]
If it is verified by following the suggestions above that this is working, I think we can close this.

**Comment by KAUTH** [comment]
The bug could not be replicated and the code is tested, see [coverage](https://app.codecov.io/gh/repository-service-tuf/repository-service-tuf-cli/blob/main/repository_service_tuf/cli/key/generate.py).
